version: "{build}"
image: Visual Studio 2019

# Uncomment to debug via RDP
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: yn73CHgZq4yvPt+v6fFUvKKA4YPZ5fyQ1JzctBZ9298=

install:

build_script:
  - ps: docker build -t docker-cli-builder .
  - ps: docker create --name cli docker-cli-builder
  - ps: docker cp cli:/gopath/src/github.com/docker/cli/build/docker.exe C:\projects\docker-cli-builder\

test_script:
  - cd C:\projects\docker-cli-builder
  - .\docker.exe --version

artifacts:
- path: .\docker.exe
  name: Binary

deploy:
  provider: GitHub
  description: ' '
  auth_token:
    secure: Q/o9y5+b/Tp/ga9XZQrb+uHYTzlR+M6J3JhsSbyBxuzkcO1ZcWD4RM4T0xOB6erV
  on:
    branch: master
    appveyor_repo_tag: true
